# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\ES\Main\UI\th.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_th(object):
    def setupUi(self, th):
        th.setObjectName("th")
        th.resize(280, 201)
        self.label_4 = QtWidgets.QLabel(th)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 54, 12))
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(th)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 261, 80))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 231, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(81, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(th)
        self.pushButton.setGeometry(QtCore.QRect(100, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(th)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 261, 72))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hang = QtWidgets.QSpinBox(self.layoutWidget1)
        self.hang.setObjectName("hang")
        self.horizontalLayout.addWidget(self.hang)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.groupBox.raise_()
        self.layoutWidget.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()

        self.retranslateUi(th)
        QtCore.QMetaObject.connectSlotsByName(th)

    def retranslateUi(self, th):
        _translate = QtCore.QCoreApplication.translate
        th.setWindowTitle(_translate("th", "Form"))
        self.label_4.setText(_translate("th", "将"))
        self.groupBox.setTitle(_translate("th", "操作"))
        self.label_5.setText(_translate("th", "全部替换为"))
        self.pushButton.setText(_translate("th", "确定"))
        self.label.setText(_translate("th", "单独替换行列"))
        self.comboBox.setItemText(0, _translate("th", "行"))
        self.comboBox.setItemText(1, _translate("th", "列"))
