# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\TaBest\Main\UI\NewFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewFile(object):
    def setupUi(self, NewFile):
        NewFile.setObjectName("NewFile")
        NewFile.resize(203, 115)
        self.gridLayout = QtWidgets.QGridLayout(NewFile)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(NewFile)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.row = QtWidgets.QSpinBox(NewFile)
        self.row.setMinimumSize(QtCore.QSize(150, 0))
        self.row.setMinimum(1)
        self.row.setMaximum(999999)
        self.row.setObjectName("row")
        self.horizontalLayout.addWidget(self.row)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(NewFile)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.hor = QtWidgets.QSpinBox(NewFile)
        self.hor.setMinimumSize(QtCore.QSize(150, 0))
        self.hor.setMinimum(1)
        self.hor.setMaximum(999999)
        self.hor.setObjectName("hor")
        self.horizontalLayout_2.addWidget(self.hor)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.Yes = QtWidgets.QPushButton(NewFile)
        self.Yes.setObjectName("Yes")
        self.verticalLayout_2.addWidget(self.Yes)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(NewFile)
        QtCore.QMetaObject.connectSlotsByName(NewFile)

    def retranslateUi(self, NewFile):
        _translate = QtCore.QCoreApplication.translate
        NewFile.setWindowTitle(_translate("NewFile", "新建文件"))
        self.label.setText(_translate("NewFile", "行数"))
        self.label_2.setText(_translate("NewFile", "列数"))
        self.Yes.setText(_translate("NewFile", "确定"))
